# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

builds:
  - id: server
    main: ./cmd/dccd
    binary: bin/dccd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath

  - id: cli
    main: ./cmd/dccctl
    binary: bin/dccctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath

  - id: conformance
    main: ./cmd/dcc-api-conformance
    binary: bin/dcc-api-conformance
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath

archives:
  - id: distribution
    ids:
      - server
      - cli
      - conformance

    formats:
      - tar.gz

    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

    wrap_in_directory: >-
      {{ .ProjectName }}_{{ .Version }}

    files:
      - README.md
      - CHANGELOG*
      - LICENSE*
      - config.example.json
      - api/*.yaml
      - docs/**/*
      - deploy/**/*

checksum:
  name_template: >-
    {{ .ProjectName }}_{{ .Version }}_sha512-checksums.txt

  algorithm: sha512
