apiVersion: 1

datasources:
  - name: TrainPilot Prometheus
    uid: trainpilot-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus.monitoring:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 2s
